events {}

http {
    include                 /etc/nginx/mime.types;

    # Redirect www HTTP to root HTTP
    server {
        listen              80;
        server_name         www.sophia-dukhota.com;
        location / {
            return 301 http://sophia-dukhota.com$request_uri;
        }
    }

    # Main root domain HTTPS block
    server {
        listen              80;
        server_name         sophia-dukhota.com;
        root                /var/www/html;
        index               index.html;
        location / {
            try_files       $uri $uri/ /index.html;
        }
        location /app {
            try_files       $uri /app/index.html;
        }
    }
}